"""add User and relationship

Revision ID: 4421450dd024
Revises: dfd12707f080
Create Date: 2022-07-19 19:11:49.830278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4421450dd024'
down_revision = 'dfd12707f080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user', type_='foreignkey')

    # ### end Alembic commands ###
