"""add RequestOrder

Revision ID: c4d193871fe6
Revises: 4421450dd024
Create Date: 2022-07-20 00:25:03.806241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d193871fe6'
down_revision = '4421450dd024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('adress_delivery', sa.String(), nullable=True),
    sa.Column('type_delivery', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_product_delivery'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_delivery'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_id'))

    op.drop_table('request')
    # ### end Alembic commands ###
